version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: microservice-fiap-hack-send-videos
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservice-fiap-hack-send-videos
    ports:
      - "5432:5432"
    volumes:
      - microservice-fiap-hack-send-videos_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: microservice-fiap-hack-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  microservice-fiap-hack-send-videos_data:
  redis_data:
